package com.teamcity.api.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.extern.jackson.Jacksonized;

/**
 * Represents a TeamCity build agent entity.
 * <p>
 * This class models a build agent in the TeamCity system. A build agent is a machine
 * that executes build processes and can be either connected or disconnected from the
 * TeamCity server.
 * </p>
 * 
 * <p>
 * The class uses Lombok annotations for automatic generation of getters, setters,
 * constructors, and other boilerplate code. It also uses Jackson annotations for
 * JSON serialization/deserialization with the TeamCity API.
 * </p>
 * 
 * @author TeamCity Testing Framework
 * @version 1.0
 * @since 1.0
 * @see BaseModel
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = false)
@Jacksonized
@JsonIgnoreProperties(ignoreUnknown = true)
public class Agent extends BaseModel {

    /**
     * Unique identifier for the agent.
     * <p>
     * This field serves as the primary key for agent identification in API calls.
     * It is typically auto-generated by the TeamCity server when an agent connects.
     * </p>
     */
    private String id;

    /**
     * The display name of the agent.
     * <p>
     * This field contains the human-readable name of the agent, which is typically
     * the hostname or a custom name assigned to the agent.
     * </p>
     */
    private String name;

}
