package com.teamcity.api.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.teamcity.api.annotations.Random;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.extern.jackson.Jacksonized;

/**
 * Represents a TeamCity user entity.
 * <p>
 * This class models a user in the TeamCity system with all necessary attributes
 * for authentication and authorization. It includes user identification, credentials,
 * and role assignments.
 * </p>
 *
 * <p>
 * The class uses Lombok annotations for automatic generation of getters, setters,
 * constructors, and other boilerplate code. It also uses Jackson annotations for
 * JSON serialization/deserialization with the TeamCity API.
 * </p>
 *
 * @author TeamCity Testing Framework
 * @version 1.0
 * @since 1.0
 * @see BaseModel
 * @see Roles
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = false)
@Jacksonized
@JsonIgnoreProperties(ignoreUnknown = true)
public class User extends BaseModel {

    /**
     * Unique identifier for the user.
     * <p>
     * This field is typically auto-generated by the TeamCity server when a new user is created.
     * It serves as the primary key for user identification in API calls.
     * </p>
     */
    private String id;

    /**
     * The username for authentication.
     * <p>
     * This field is marked with @Random annotation, meaning it will be automatically
     * generated with random values during test data creation to ensure uniqueness.
     * </p>
     */
    @Random
    private String username;

    /**
     * The email address associated with the user.
     * <p>
     * This field is marked with @Random annotation, meaning it will be automatically
     * generated with random values during test data creation to ensure uniqueness.
     * </p>
     */
    @Random
    private String email;

    /**
     * The password for user authentication.
     * <p>
     * This field is marked with @Random annotation, meaning it will be automatically
     * generated with random values during test data creation for security purposes.
     * </p>
     */
    @Random
    private String password;

    /**
     * The roles assigned to this user.
     * <p>
     * Contains information about the user's permissions and access levels within
     * the TeamCity system.
     * </p>
     *
     * @see Roles
     */
    private Roles roles;

}
