name: Report

on:
  workflow_call:
    inputs:
      parent_run_number:
        required: false
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Репозиторий (скрипты, стили и т.п.)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Артефакты тестов -> allure-results/
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      # 3) Рабочее дерево опубликованного сайта (ветка gh-pages)
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # 4) Сборка Allure в gh-pages БЕЗ авто-push
      - name: Build Allure (no auto push)
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages                  # action положит отчёт в gh-pages/<run>/
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: true

      - name: Отладка и перенос Allure в /allure-report/ (одним шагом)
        shell: bash
        run: |
          set -euo pipefail
          # Определяем номер запуска: берём входной, иначе текущий run_number
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi
          
          RUN_DIR="gh-pages/${RUN}"
          DEST="${RUN_DIR}/allure-report"
          
          # --- Отладочная печать входных артефактов ---
          echo "=== allure-results (2 уровня) ==="
          find allure-results -maxdepth 2 -print 2>/dev/null | sort || true
          
          # --- Проверяем, что директория публикации существует ---
          echo "=== Проверка директории публикации: $RUN_DIR ==="
          if [ ! -d "$RUN_DIR" ]; then
            echo "Директория $RUN_DIR не найдена. Похоже, шаг сборки Allure не создал выходные файлы."
            echo "Дерево gh-pages (2 уровня):"
            find gh-pages -maxdepth 2 -type d -print | sort || true
            exit 1
          fi
          
          # --- Проверяем, что в $RUN_DIR действительно есть артефакты Allure ---
          if ! { [ -f "$RUN_DIR/index.html" ] || [ -f "$RUN_DIR/app.js" ] || [ -d "$RUN_DIR/data" ]; }; then
            echo "В $RUN_DIR не найдено типичных файлов Allure (index.html/app.js/data). Перенос пропускаем."
            echo "Содержимое корня ран-а:"
            find "$RUN_DIR" -maxdepth 1 -mindepth 1 -print | sort || true
            exit 0
          fi
          
          # --- Печатаем текущие файлы перед переносом ---
          echo "=== Содержимое $RUN_DIR (до переноса) ==="
          find "$RUN_DIR" -maxdepth 1 -mindepth 1 -print | sort
          
          # --- Переносим всё в /allure-report/, кроме того, что должно остаться в корне run-а ---
          mkdir -p "$DEST"
          # Включаем расширенные шаблоны и захват скрытых файлов
          shopt -s extglob dotglob nullglob
          # Исключаем: уже существующую папку отчёта, папку swagger, а также файлы метрик/стилей/логотип
          mv "$RUN_DIR"/!(allure-report|swagger-coverage-report|metrics.json|report_styles.css|logo_icon.png) "$DEST"/ || true
          
          # --- Печать после переноса ---
          echo "=== После переноса — $DEST ==="
          find "$DEST" -maxdepth 2 -print | sort
          echo "=== После переноса — корень ран-а $RUN_DIR ==="
          find "$RUN_DIR" -maxdepth 2 -print | sort
      

      # 6) Кладём Swagger рядом
      - name: Add Swagger coverage to published site
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          DEST="gh-pages/${RUN}/swagger-coverage-report"
          mkdir -p "$DEST"

          if [ -f "allure-results/swagger-coverage-report.html" ]; then
            cp "allure-results/swagger-coverage-report.html" "$DEST/index.html"
          else
            echo "No swagger-coverage-report.html found in allure-results/"
            ls -la allure-results || true
          fi

      # 7) (Опционально) брендинг + метрики по опубликованным путям
      - name: Copy branding and generate metrics
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi
          RUN_DIR="gh-pages/${RUN}"

          # Опциональные файлы брендинга
          [ -f .github/report/logo_icon.png ]     && cp .github/report/logo_icon.png     "$RUN_DIR/" || true
          [ -f .github/report/report_styles.css ] && cp .github/report/report_styles.css "$RUN_DIR/" || true

          # Пути для скрипта метрик
          ALLURE_DIR="$RUN_DIR/allure-report"                 # тут index.html, data/, widgets/
          SWAGGER_DIR="$RUN_DIR/swagger-coverage-report"      # тут index.html Swagger
          OUT_DIR="$RUN_DIR"                                  # сюда писать метрики/дашборд

          if [ -f .github/scripts/extract-metrics.sh ]; then
            chmod +x .github/scripts/extract-metrics.sh || true
            # ВАЖНО: внутри скрипта не использовать sudo для записи в gh-pages/*
            .github/scripts/extract-metrics.sh "$ALLURE_DIR" "$SWAGGER_DIR" "$OUT_DIR"
          else
            echo "extract-metrics.sh not found; skipping metrics generation"
          fi

      # 8) Нормализация прав (на случай, если где-то писали от root)
      - name: Normalize ownership and permissions in gh-pages
        shell: bash
        run: |
          set -euo pipefail
          sudo chown -R "$(id -u):$(id -g)" gh-pages
          find gh-pages -type d -exec chmod 755 {} \;
          find gh-pages -type f -exec chmod 644 {} \;
          git config --global --add safe.directory "$GITHUB_WORKSPACE/gh-pages"

      # 9) Публикация одним коммитом
      - name: Publish Allure + Swagger + Dashboard (single push)
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          echo "Preview tree:"
          find gh-pages -maxdepth 3 -type f | sort | sed -n '1,200p'

          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Allure (/allure-report), Swagger and dashboard for run ${RUN}" || echo "Nothing to commit"
          git push
