name: Report

on:
  workflow_call:
    inputs:
      parent_run_number:
        required: false
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Source repo (to get scripts, .github, etc.)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Download test artifacts -> allure-results/
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      # 3) Checkout gh-pages (published site working tree)
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # 4) Build Allure into gh-pages (no auto push)
      - name: Build Allure (no auto push)
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages                  # where the SPA will be written
          allure_history: allure-history      # history cache dir (local workspace)
          allure_results: allure-results      # input results
          keep_reports: true                  # <— crucial: do not push

      # 5) Add Swagger coverage HTML next to the run folder
      - name: Add Swagger coverage to published site
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ github.run_number }}"
          DEST="gh-pages/${RUN}/swagger-coverage-report"
          mkdir -p "$DEST"

          if [ -f "allure-results/swagger-coverage-report.html" ]; then
            cp "allure-results/swagger-coverage-report.html" "$DEST/index.html"
          else
            echo "No swagger-coverage-report.html found in allure-results/"
            ls -la allure-results || true
          fi

      # 6) Copy branding & generate metrics against the PUBLISHED paths
      - name: Extract metrics and generate dashboard
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ github.run_number }}"
          RUN_DIR="gh-pages/${RUN}"

          # Optional branding
          [ -f .github/report/logo_icon.png ]    && cp .github/report/logo_icon.png    "$RUN_DIR/" || true
          [ -f .github/report/report_styles.css ]&& cp .github/report/report_styles.css "$RUN_DIR/" || true

          # Paths for metrics script:
          ALLURE_DIR="$RUN_DIR"                                # Allure SPA lives here (index.html, data/, widgets/)
          SWAGGER_DIR="$RUN_DIR/swagger-coverage-report"       # Swagger HTML we just copied
          OUT_DIR="$RUN_DIR"                                   # where to write dashboard

          chmod +x .github/scripts/extract-metrics.sh
          .github/scripts/extract-metrics.sh "$ALLURE_DIR" "$SWAGGER_DIR" "$OUT_DIR"
          echo "Metrics extracted and dashboard generated"

      # 7) Publish (single push)
      - name: Publish Allure + Swagger (single push)
        shell: bash
        run: |
          set -euo pipefail
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Allure + Swagger for run ${{ github.run_number }}" || echo "Nothing to commit"
          git push
