name: Report

on:
  workflow_call:
    inputs:
      parent_run_number:
        required: false
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Repo (scripts, workflow files, etc.)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Test artifacts -> allure-results/
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      # 3) Published site working tree
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # 4) Build Allure into gh-pages (no auto push)
      - name: Build Allure (no auto push)
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: true

      # 5) Add Swagger next to the run folder
      - name: Add Swagger coverage to published site
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          DEST="gh-pages/${RUN}/swagger-coverage-report"
          mkdir -p "$DEST"

          if [ -f "allure-results/swagger-coverage-report.html" ]; then
            cp "allure-results/swagger-coverage-report.html" "$DEST/index.html"
          else
            echo "No swagger-coverage-report.html found in allure-results/"
            ls -la allure-results || true
          fi

      # 6) Optional: branding + metrics generated against the PUBLISHED paths
      - name: Copy branding and generate metrics
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi
          RUN_DIR="gh-pages/${RUN}"

          # Optional branding
          [ -f .github/report/logo_icon.png ] && cp .github/report/logo_icon.png "$RUN_DIR/" || true
          [ -f .github/report/report_styles.css ] && cp .github/report/report_styles.css "$RUN_DIR/" || true

          # Paths for metrics script
          ALLURE_DIR="$RUN_DIR"                          # Allure SPA output (index.html, data/, widgets/)
          SWAGGER_DIR="$RUN_DIR/swagger-coverage-report" # Swagger HTML we just copied
          OUT_DIR="$RUN_DIR"                             # Where to write metrics/dashboard

          if [ -f .github/scripts/extract-metrics.sh ]; then
            chmod +x .github/scripts/extract-metrics.sh || true
            .github/scripts/extract-metrics.sh "$ALLURE_DIR" "$SWAGGER_DIR" "$OUT_DIR"
          else
            echo "extract-metrics.sh not found; skipping metrics generation"
          fi

      # 7) Single publish (commit + push)
      - name: Publish Allure + Swagger (single push)
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          # Avoid dubious ownership errors
          git config --global --add safe.directory "$GITHUB_WORKSPACE/gh-pages"

          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Allure + Swagger for run ${RUN}" || echo "Nothing to commit"
          git push
