name: Report

on:
  workflow_call:
    inputs:
      parent_run_number:
        required: false
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Репозиторий (скрипты, workflow, extract-metrics.sh и т.п.)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Скачиваем артефакты тестов в allure-results/ (сливаем все артефакты)
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      # 3) Рабочее дерево опубликованного сайта (ветка gh-pages)
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # 4) Устанавливаем Java (нужна Allure CLI)
      - name: Setup Java (for Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 5) Устанавливаем Allure CLI
      - name: Install Allure CLI
        shell: bash
        run: |
          set -euo pipefail
          VER="2.29.0"
          curl -sSL -o "allure-${VER}.tgz" "https://github.com/allure-framework/allure2/releases/download/${VER}/allure-${VER}.tgz"
          sudo tar -zxvf "allure-${VER}.tgz" -C /opt/
          sudo ln -sf "/opt/allure-${VER}/bin/allure" /usr/bin/allure
          allure --version

      # 6) Подготовка history: переносим историю прошлого прогона в allure-results/history (если есть)
      - name: Prepare Allure history
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          # Ищем последний опубликованный ран с allure-report/history
          PREV="$(ls -d gh-pages/*/allure-report 2>/dev/null | sed -E 's|gh-pages/([0-9]+)/allure-report|\1|' | grep -E '^[0-9]+$' | sort -n | tail -1 || true)"
          echo "Detected previous run: ${PREV:-<none>}"

          if [ -n "$PREV" ] && [ -d "gh-pages/${PREV}/allure-report/history" ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/${PREV}/allure-report/history/* allure-results/history/ || true
            echo "History copied from gh-pages/${PREV}/allure-report/history -> allure-results/history"
          else
            echo "No previous history found"
          fi

          echo "== allure-results top-level =="
          find allure-results -maxdepth 1 -type f | sort | head -n 50 || true

      # 7) Генерируем Allure в gh-pages/<run>/allure-report
      - name: Generate Allure report to /allure-report/
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          OUT="gh-pages/${RUN}/allure-report"
          mkdir -p "$OUT"
          # Собираем отчёт из allure-results
          allure generate --clean "allure-results" -o "$OUT"

          echo "== Generated tree =="
          find "gh-pages/${RUN}" -maxdepth 2 -print | sort

      # 8) Кладём Swagger рядом: gh-pages/<run>/swagger-coverage-report/index.html
      - name: Add Swagger coverage to published site
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          DEST="gh-pages/${RUN}/swagger-coverage-report"
          mkdir -p "$DEST"
          if [ -f "allure-results/swagger-coverage-report.html" ]; then
            cp "allure-results/swagger-coverage-report.html" "$DEST/index.html"
          else
            echo "No swagger-coverage-report.html found in allure-results/"
            ls -la allure-results || true
          fi

      # 9) (Опционально) брендинг и генерация метрик по уже опубликованным путям
      - name: Copy branding and generate metrics
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi
          RUN_DIR="gh-pages/${RUN}"
          
          # Опциональные файлы брендинга (если есть)
          [ -f .github/report/logo_icon.png ]     && cp .github/report/logo_icon.png     "$RUN_DIR/" || true
          [ -f .github/report/report_styles.css ] && cp .github/report/report_styles.css "$RUN_DIR/" || true
          
          # Пути для скрипта метрик
          ALLURE_DIR="$RUN_DIR/allure-report"
          SWAGGER_DIR="$RUN_DIR/swagger-coverage-report"
          OUT_DIR="$RUN_DIR"
          
          # Базовый префикс ссылок, например /w1/23/
          REPO="${GITHUB_REPOSITORY#*/}"   # "w1"
          BASE_PREFIX="/${REPO}/${RUN}/"
          
          if [ -f .github/scripts/extract-metrics.sh ]; then
            chmod +x .github/scripts/extract-metrics.sh || true
            .github/scripts/extract-metrics.sh "$ALLURE_DIR" "$SWAGGER_DIR" "$OUT_DIR" "$BASE_PREFIX"
          else
            echo "extract-metrics.sh not found; skipping metrics"
          fi
          
          # (опционально) быстрый просмотр того, что получилось
          echo "== Result files in ${RUN_DIR} =="
          find "$RUN_DIR" -maxdepth 2 -type f | sort


      # 10) Нормализуем владельца/права, чтобы git add не упал из-за Permission denied
      - name: Normalize ownership and permissions in gh-pages
        shell: bash
        run: |
          set -euo pipefail
          sudo chown -R "$(id -u):$(id -g)" gh-pages
          find gh-pages -type d -exec chmod 755 {} \;
          find gh-pages -type f -exec chmod 644 {} \;
          git config --global --add safe.directory "$GITHUB_WORKSPACE/gh-pages"

      # 11) Публикуем всё одним коммитом
      - name: Publish Allure + Swagger + Dashboard (single push)
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi

          echo "== Preview to publish =="
          find gh-pages -maxdepth 3 -type f | sort | sed -n '1,200p'

          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Publish Allure (/allure-report), Swagger and dashboard for run ${RUN}" || echo "Nothing to commit"
          git push

      # 12) Отправляем уведомление в Telegram
      - name: Send Telegram notification
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          RUN="${{ inputs.parent_run_number }}"
          if [ -z "$RUN" ]; then RUN="${{ github.run_number }}"; fi
          
          # Определяем статус выполнения
          if [ "${{ job.status }}" = "success" ]; then
            STATUS_EMOJI="✅"
            STATUS_TEXT="SUCCESS"
          elif [ "${{ job.status }}" = "failure" ]; then
            STATUS_EMOJI="❌"
            STATUS_TEXT="FAILED"
          else
            STATUS_EMOJI="⚠️"
            STATUS_TEXT="CANCELLED"
          fi
          
          # Формируем сообщение (экранируем специальные символы для JSON)
          MESSAGE="🚀 *Test Execution Report* ${STATUS_EMOJI}

          *Status:* ${STATUS_TEXT}
          *Run Number:* ${RUN}
          *Repository:* ${{ github.repository }}
          *Branch:* ${{ github.ref_name }}
          *Commit:* \`${{ github.sha }}\`

          📊 *Test Report:* https://nobugs-projects.github.io/w1/${RUN}/

          🔗 *Allure Report:* https://nobugs-projects.github.io/w1/${RUN}/allure-report/
          🔍 *Swagger Coverage:* https://nobugs-projects.github.io/w1/${RUN}/swagger-coverage-report/

          *Workflow:* ${{ github.workflow }}
          *Triggered by:* ${{ github.actor }}"
          
          # Экранируем сообщение для JSON
          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed 's/"/\\"/g' | sed 's/\\/\\\\/g')
          
          # Отправляем сообщение в Telegram с обработкой ошибок
          echo "Sending Telegram notification..."
          TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
          TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
          
          # Validate required secrets
          if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
            echo "❌ TELEGRAM_BOT_TOKEN secret is not set"
            exit 1
          fi
          
          if [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ TELEGRAM_CHAT_ID secret is not set"
            exit 1
          fi
          
          echo "Bot Token: ${TELEGRAM_BOT_TOKEN:0:10}..."
          echo "Chat ID: $TELEGRAM_CHAT_ID"
          
          # Test bot token first
          echo "Testing bot token..."
          BOT_TEST_RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" || echo "HTTPSTATUS:000")
          BOT_TEST_HTTP_STATUS=$(echo $BOT_TEST_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          
          if [ "$BOT_TEST_HTTP_STATUS" -ne 200 ]; then
            echo "❌ Bot token is invalid. HTTP Status: $BOT_TEST_HTTP_STATUS"
            echo "Response: $(echo $BOT_TEST_RESPONSE | sed -e 's/HTTPSTATUS:.*//g')"
            exit 1
          fi
          
          echo "✅ Bot token is valid"
          
          RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"${TELEGRAM_CHAT_ID}\",
              \"text\": \"${ESCAPED_MESSAGE}\",
              \"parse_mode\": \"Markdown\",
              \"disable_web_page_preview\": false
            }" || echo "HTTPSTATUS:000")
          
          HTTP_STATUS=$(echo $RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          RESPONSE_BODY=$(echo $RESPONSE | sed -e 's/HTTPSTATUS:.*//g')
          
          echo "HTTP Status: $HTTP_STATUS"
          echo "Response: $RESPONSE_BODY"
          
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Telegram notification sent successfully"
          else
            echo "❌ Failed to send Telegram notification. HTTP Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            exit 1
          fi
